version: "3"
services:
#  eureka-naming-server:
#    build:
#      context: ../EurekaNamingServer
#      dockerfile: Dockerfile
#    container_name: naming-server
#    ports:
#      - 8761:8761
#    networks:
#      - e-stock-market
  
  manage-company-service:
    build:
      context: ../ManageCompanyService
      dockerfile: Dockerfile
    container_name: company-service
    ports:
      - 8000:8000
    depends_on:
      #- eureka-naming-server
      - mysqldb
    environment:
      EUREKA_URI: http://eureka-naming-server:8761/eureka
      MYSQL_HOST: mysqldb
    networks:
      - e-stock-market
 
  mysqldb:
    image: mysql/mysql-server
    container_name: mysql-server-standalone
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: manage_company  
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - e-stock-market

networks:
  e-stock-market:

volumes:
  mysqldata: