version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-server
    ports:
      - 2181:2181
    networks:
      - e-stock-market
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-server
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
#HostIP of docker host_machine(localhost or 127.0.0.1)
      KAFKA_ADVERTISED_HOST_NAME: 192.168.56.1 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#New topic with name "company-service-topic" , 1 partition & 2 replication factor 
      KAFKA_CREATE_TOPICS: "company-service-topic:1:2,stock-service-topic:1:2"
    volumes:
      - kafkadata:/var/run/docker.sock
    networks:
      - e-stock-market
  
networks:
  e-stock-market:

volumes:
  kafkadata: