version: "3"
services:
  eureka-naming-server:
    build:
      context: ../EurekaNamingServer
      dockerfile: Dockerfile
    container_name: naming-server
    ports:
      - 8761:8761
    networks:
      - e-stock-market
  
  stock-service:
    build:
      context: ../StockService
      dockerfile: Dockerfile
    container_name: stock-service
    ports:
      - 9000:9000
    depends_on:
      - eureka-naming-server
      - mongodb
    environment:
      EUREKA_URI: http://eureka-naming-server:8761/eureka
      MONGO_HOST: mongodb
    networks:
      - e-stock-market

  mongodb:
    image: mongo
    container_name: mongo-server-standalone
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - e-stock-market

networks:
  e-stock-market:

volumes:
  mongodata: